# Generated by Django 4.2 on 2023-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=5000)),
                ("code_answer", models.TextField(max_length=5000)),
                ("language", models.CharField(max_length=100)),
            ],
        ),
    ]
